🛡️ Villager now have arrow protection aura (close #102)
Gunivers/Scaffolding-Rush pull request #108
Opened 2023-04-11 15:15 UTC by Leirof

2023-04-11 16:04 UTC, Theaustudio requested changes

2023-04-11 16:04 UTC, Theaustudio commented on datapacks/Scaffolding Rush/data/scaffolding_rush/functions/villager/arrow_shield.mcfunction
> +execute as @e[type=villager] positioned ~ ~1 ~ at @e[type=arrow,distance=..3] run playsound minecraft:block.amethyst_cluster.break master @a[distance=..30] ~ ~ ~ 2 2 1
je baisserais le volume à 0.5 et pas de volume minimum car tout le monde n'a pas besoin de l'entendre

2023-04-18 22:01 UTC, Loumardes approved these changes

2023-04-18 22:02 UTC, Loumardes commented
je sais pas trop comment ça marche

2023-04-20 09:14 UTC, Leirof commented
A chaque tick, chaque villageois identifie les flèches dans un rayon de 5 blocks autour de lui via un tag.

https://github.com/Gunivers/Blazing-Scaffolding/blob/b76c9989d6e846e9dd50f5c6b8e27adacd32fc14/datapacks/Scaffolding%20Rush/data/scaffolding_rush/functions/villager/arrow_shield.mcfunction#L4

Le vecteur séparant la flèche du villageois est alors récupérer via la Glib, puis normalisé 

https://github.com/Gunivers/Blazing-Scaffolding/blob/b76c9989d6e846e9dd50f5c6b8e27adacd32fc14/datapacks/Scaffolding%20Rush/data/scaffolding_rush/functions/villager/arrow_shield.mcfunction#L6-L8

Ensuite, le vecteur de mouvement de la flèche est récupéré depuis ses propriété motions et également normalisé

https://github.com/Gunivers/Blazing-Scaffolding/blob/b76c9989d6e846e9dd50f5c6b8e27adacd32fc14/datapacks/Scaffolding%20Rush/data/scaffolding_rush/functions/villager/arrow_shield.mcfunction#L11-L13

De là je fais un produit scalaire entre les deux vecteurs ($=X1*X2 + Y1*Y2 + Z1*Z2$)

Puis je kill les flèches ayant un produit scalaire supérieur à 0,5 (-> 500 vu que MC ne gère pas les décimales donc j'élève toutes les quantités à $10^3$)

https://github.com/Gunivers/Blazing-Scaffolding/blob/b76c9989d6e846e9dd50f5c6b8e27adacd32fc14/datapacks/Scaffolding%20Rush/data/scaffolding_rush/functions/villager/arrow_shield.mcfunction#L18-L24

La fonction "laser" permet simplement de créer une ligne de particule entre le villageois et la flèche, ayannt la couleur de l'équipe, de sorte à indiquer explicitement que la flèche à été détruire par le villageois (et ne pas laisser les joueurs s'interroger sur pourquoi leurs flèches ont été détruites)

https://github.com/Gunivers/Blazing-Scaffolding/blob/b76c9989d6e846e9dd50f5c6b8e27adacd32fc14/datapacks/Scaffolding%20Rush/data/scaffolding_rush/functions/villager/arrow_shield_laser.mcfunction#L1-L16

Pour ce qui est de la modification des fichiers de la lib, ils peuvent être vu de façon indépendantes. Chaque fonction à pour but de réaliser une opération particulière sur un trio de scores qui représente le vecteur que la fonction manipule.

Si il y a une fonction en particulier que tu ne comprends pas, dis moi, j'essayerais de t'expliquer ça ^^

2023-04-22 16:14 UTC, Leirof commented
Yolomerge activated (accord de loumardes)

2023-04-22 16:14 UTC, merged