Flying villager
Gunivers/Scaffolding-Rush pull request #37
Opened 2022-08-18 17:27 UTC by ascpial

Closes #33.
This PR resolve the issue with the flying villager.
The cause was that the command was trying to use a removed block tag.

2022-08-18 18:45 UTC, LeiRoF requested changes
Add also the cave_air in order to avoid bugs with the anti-ghost block system that use cave_air

2022-08-18 19:47 UTC, Loumardes commented
the cave air should not mattea as it revert it back to air instantly

2022-08-18 19:59 UTC, LeiRoF commented
It should not matter, but it does ^^'
With the volcano feature I also need to detect if the lava projection is in the air, and sometimes the projection passes through a cave_air so it blowed. I don't know how but some cave_air remain ^^'

2022-08-19 08:03 UTC, LeiRoF approved these changes

2022-08-19 08:05 UTC, merged